### ISSUE TITLE
Giving credit where it is due

### ISSUE THREAD

**Issue by rmccorm4** [araut1/Convolutional-Neural-Network-Project#1]
Hi Abhishek,

This code is clearly taken from my repository (https://github.com/HackBinghamton/CNN-Demo), I'd appreciate some sort of credit to me listed somewhere as opposed to claiming it as your own work.

Thanks,
Ryan

**Comment by araut1** [comment]
Hi Ryan,

Thanks for notifying. I am busy right now, by evening I will make necessary
changes for credit.

I deeply apologise for the inconvenience.

Best,
Abhishek

Sent on the go

**Comment by araut1** [comment]
Hi,

I have written a citation in the README.md file.

Please feel free to let me know if anything else is required.

Regards,
Abhishek

**Comment by rmccorm4** [comment]
Looks good, thank you for doing that.
